### ISSUE TITLE
Cephei error after respring

### ISSUE THREAD

**Issue by Haeckli** [Randy-420/VolumeStep13#1]
I just updates to Version 0.1.1 and since then after each respring i get this popup (see attached screenshot)...
![B5B917DD-82C1-4561-8EA4-55DACAC46B13](https://user-images.githubusercontent.com/26849758/102530837-cc834780-40a1-11eb-8acb-2b86d927035d.png)

**Comment by Randy-420** [comment]
Fixed in new update - sorry about that.
